### ISSUE TITLE
ISSUE WITH 404

### ISSUE THREAD

**Issue by UmaAjay** [Narendra03K/Placement-Portal#2]
after cloning  the website , i am getting this type of error like it showing URL not found like i mentioned below

**Not Found**

The requested URL was not found on this server.

Apache/2.4.54 (Win64) OpenSSL/1.1.1p PHP/8.1.12 Server at localhost Port 80

**Comment by 19481A1281** [comment]
will you please resolve this error :

The requested URL was not found on this server.

Apache/2.4.54 (Win64) OpenSSL/1.1.1p PHP/8.1.12 Server at localhost Port 80

**Comment by Narendra03K** [comment]
please make sure, xampp/ wampp server is running in the background and database is connected.
